/** 에이전트 카탈로그와 브라우저가 공유하는 호출 표시 이름. */
export const CALL_LABELS = {
  accept_manager_offer: "감독직 수락",
  counter_manager_offer: "감독 계약 조건 수정",
  apply_manager_job: "감독직 지원",
  hire_staff: "스태프 고용·재계약",
  release_staff: "스태프 계약 해지",
  resign: "사임",
  start_negotiation: "협상 시작",
  get_negotiations: "협상 목록 조회",
  set_transfer_list: "이적 명단 변경",
  start_match: "경기 시작",
  tactic_orders: "전술 지시",
  training_orders: "훈련 지시",
  finance_orders: "재정 지시",
  set_lineup: "라인업",
  set_squad_level: "1·2군 이동",
  set_captain: "완장 지정",
  set_squad_number: "등번호",
  set_development_focus: "집중 육성",
  sign_youth: "유스 첫 계약",
  set_tactics: "팀 전술 변경",
  set_player_tactic: "선수 전술",
  set_set_piece_takers: "세트피스 키커",
  set_set_piece_routine: "세트피스 인원",
  set_training: "훈련 지정",
  set_shootout_order: "승부차기 순서",
  update_character: "로어북 갱신",
  review_board: "감독 고용 결정",
  offer_manager_job: "감독직 제안",
  set_retirement: "은퇴 결정",
  respond_to_interview: "감독직 면접 응답",
  substitute: "선수 교체",
  apply_finance_event: "재정 이벤트",
  request_board: "보드에 요청",
  set_ticket_price: "티켓 가격",
  search_players: "선수 검색",
  get_squad: "스쿼드·라인업 조회",
  get_team: "팀 조회",
  get_league: "리그·일정 조회",
  get_career: "커리어 조회",
  get_history: "역대 기록 조회",
  get_finance: "재정 조회",
  get_match_report: "경기 리포트",
  get_opponent_report: "상대 분석",
  // 도구가 아니라 코어가 남기는 기록 — 카탈로그에 없지만 칩으로 선다
  finalize_match: "경기 종료",
} as const;
